# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c7bb39f443514635323f526649c48303969dfac476f60e0d0c3573f024728654b049640b8b4600446a83ed55c15c831e8b26008f9c431a5f62398f39cedcf1b

test:
  secret_key_base: 3a476487ac7210cd3d175abe56cbb527fc96d4eca02c720d6d7e4da8150f1841e621da360ba89484d7ed7cbbf7556deb0f00daf9a9bc92967f92811b3763756e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
